# Generated by Django 4.1.7 on 2023-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(default=None, to='users.member'),
        ),
        migrations.AlterField(
            model_name='team',
            name='projects',
            field=models.ManyToManyField(default=None, to='projects.project'),
        ),
    ]
