# Generated by Django 4.1.7 on 2023-04-02 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_member_user_team_name_alter_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
