# Generated by Django 4.1.7 on 2023-05-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_team_projects'),
        ('projects', '0002_alter_project_tasks_tasksgroup_project_tasks_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner_team',
            field=models.ManyToManyField(default=None, to='users.team'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'owner'), ('2', 'admin'), ('3', 'workers')], max_length=8)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(default=None, through='projects.ProjectMembership', to='users.member'),
        ),
    ]
